# Sets the default pinentry program to use the ncurses interface
pinentry-program /usr/bin/pinentry-curses

# allow clients to use the loopback pinentry features
allow-loopback-pinentry

# set the time a chace entry is valid to 20minutes
default-cache-ttl 1200

# ssh support
enable-ssh-support
